import { Button, VerticalBox, GridBox, GroupBox, HorizontalBox, ListView, CheckBox } from "std-widgets.slint";
import { Globals } from "globals.slint";
import { OptionsCheckbox } from "options-checkbox.slint";
import { MenuTab, Level } from "types.slint";
import { MenuButton } from "menu-button.slint";
import { PlayTab } from "play-tab.slint";

component GalleryTab { }

component OptionsTab inherits VerticalLayout {
    spacing: 16px;

    OptionsCheckbox {
        text: "Fullscreen";
        // width: 256px;
    }

    OptionsCheckbox {
        text: "Show FPS";
        // width: 64px;
    }
}

export component AppWindow inherits Window {
    width: 1024px;
    height: 768px;

    // preferred-width: 1024px;
    // preferred-height: 768px;

    in-out property <string> level_path;

    callback request_exit();
    callback request_play_level();

    HorizontalLayout {
        padding: 16px;

        VerticalLayout {
            width: 20%;
            spacing: 8px;
            alignment: start;

            MenuButton {
                menu-tab: MenuTab.Play;
                text: "Play";
                clicked => {
                    Globals.active-menu-tab = MenuTab.Play
                }
            }

            MenuButton {
                menu-tab: MenuTab.Gallery;
                text: "Gallery";
                clicked => {
                    Globals.active-menu-tab = MenuTab.Gallery
                }
            }

            MenuButton {
                menu-tab: MenuTab.Options;
                text: "Options";
                clicked => {
                    Globals.active-menu-tab = MenuTab.Options
                }
            }

            MenuButton {
                menu-tab: MenuTab.About;
                text: "About";
                clicked => {
                    Globals.active-menu-tab = MenuTab.About
                }
            }

            MenuButton {
                menu-tab: MenuTab.None;
                text: "Exit";
                clicked => {
                    root.request_exit();
                }
            }
        }

        VerticalLayout {
            padding-left: 16px;
            horizontal-stretch: 1;
            vertical-stretch: 1;

            if Globals.active-menu-tab == MenuTab.Play: PlayTab {
                request_play_level(path) => {
                    root.level_path = path;
                    root.request_play_level();
                }
            }

            if Globals.active-menu-tab == MenuTab.Options: OptionsTab { }
        }
    }
}
