import { Button, VerticalBox, GridBox, GroupBox, HorizontalBox, ListView, CheckBox } from "std-widgets.slint";
import { Globals } from "globals.slint";
import { MenuTab, Level, GameStats } from "types.slint";
import { MenuButton } from "menu-button.slint";
import { PlayTab } from "play-tab.slint";
import { GalleryTab, ImageDialog } from "gallery-tab.slint";
import { OptionsTab } from "options-tab.slint";
import { AboutTab } from "about-tab.slint";

export { ImageDialog }

export component AppWindow inherits Window {
    title: "Templar's Hollow Alpha";
    icon: @image-url("../images/icon.png");
    width: 1024px;
    height: 768px;

    in-out property <string> level_path;
    in-out property <string> url_to_open;
    in-out property <bool> is_fullscreen;
    in-out property <bool> should_show_fps;
    in property <[GameStats]> game_stats;

    callback request_exit();
    callback request_play_level();
    callback request_open_image(string, image);

    // Background image
    Image {
        source: @image-url("../images/background6.png");
        width: 100%;
        height: 100%;
        image-fit: cover;
    }

    HorizontalLayout {
        padding: 16px;

        VerticalLayout {
            width: 15%;
            spacing: 8px;
            alignment: start;

            MenuButton {
                menu-tab: MenuTab.Play;
                text: "Play";
                clicked => {
                    Globals.active-menu-tab = MenuTab.Play
                }
            }

            MenuButton {
                menu-tab: MenuTab.Gallery;
                text: "Gallery";
                clicked => {
                    Globals.active-menu-tab = MenuTab.Gallery
                }
            }

            MenuButton {
                menu-tab: MenuTab.Options;
                text: "Options";
                clicked => {
                    Globals.active-menu-tab = MenuTab.Options
                }
            }

            MenuButton {
                menu-tab: MenuTab.About;
                text: "About";
                clicked => {
                    Globals.active-menu-tab = MenuTab.About
                }
            }

            MenuButton {
                menu-tab: MenuTab.None;
                text: "Exit";
                clicked => {
                    root.request_exit();
                }
            }
        }

        VerticalLayout {
            padding-left: 16px;
            horizontal-stretch: 1;
            vertical-stretch: 1;

            if Globals.active-menu-tab == MenuTab.Play: PlayTab {
                game_stats: root.game_stats;
                request_play_level(path) => {
                    root.level_path = path;
                    root.request_play_level();
                }
            }

            if Globals.active-menu-tab == MenuTab.Gallery: GalleryTab {
                game_stats: root.game_stats;
                request_open_image(title, image) => {
                    root.request_open_image(title, image);
                }
            }

            if Globals.active-menu-tab == MenuTab.Options: OptionsTab {
                is_fullscreen <=> root.is_fullscreen;
                should_show_fps <=> root.should_show_fps;
            }

            if Globals.active-menu-tab == MenuTab.About: AboutTab { }
        }
    }
}
