import { Button, VerticalBox, GridBox, GroupBox, HorizontalBox, ListView, CheckBox } from "std-widgets.slint";
import { Globals } from "globals.slint";
import { OptionsCheckbox } from "options-checkbox.slint";
import { MenuTab, Level } from "types.slint";
import { MenuButton } from "menu-button.slint";
import { PlayTab } from "play-tab.slint";

component GalleryTab { }

component OptionsTab inherits VerticalLayout {
    in-out property <bool> is_fullscreen <=> fullscreen_checkbox.checked;
    in-out property <bool> should_show_fps <=> show_fps_checkbox.checked;

    spacing: 16px;

    fullscreen_checkbox := OptionsCheckbox {
        text: "Fullscreen";
    }

    show_fps_checkbox := OptionsCheckbox {
        text: "Show FPS";
    }
}

export component AppWindow inherits Window {
    width: 1024px;
    height: 768px;

    // preferred-width: 1024px;
    // preferred-height: 768px;

    in-out property <string> level_path;
    in-out property <bool> is_fullscreen <=> options_tab.is_fullscreen;
    in-out property <bool> should_show_fps <=> options_tab.should_show_fps;

    callback request_exit();
    callback request_play_level();

    HorizontalLayout {
        padding: 16px;

        VerticalLayout {
            width: 20%;
            spacing: 8px;
            alignment: start;

            MenuButton {
                menu-tab: MenuTab.Play;
                text: "Play";
                clicked => {
                    Globals.active-menu-tab = MenuTab.Play
                }
            }

            MenuButton {
                menu-tab: MenuTab.Gallery;
                text: "Gallery";
                clicked => {
                    Globals.active-menu-tab = MenuTab.Gallery
                }
            }

            MenuButton {
                menu-tab: MenuTab.Options;
                text: "Options";
                clicked => {
                    Globals.active-menu-tab = MenuTab.Options
                }
            }

            MenuButton {
                menu-tab: MenuTab.About;
                text: "About";
                clicked => {
                    Globals.active-menu-tab = MenuTab.About
                }
            }

            MenuButton {
                menu-tab: MenuTab.None;
                text: "Exit";
                clicked => {
                    root.request_exit();
                }
            }
        }

        VerticalLayout {
            padding-left: 16px;
            horizontal-stretch: 1;
            vertical-stretch: 1;

            PlayTab {
                visible: Globals.active-menu-tab == MenuTab.Play;

                request_play_level(path) => {
                    root.level_path = path;
                    root.request_play_level();
                }
            }

            options_tab := OptionsTab {
                visible: Globals.active-menu-tab == MenuTab.Options;
            }
        }
    }
}
