import { ListView, Button } from "std-widgets.slint";
import { GalleryItem, GameStats } from "types.slint";
import { Globals } from "globals.slint";

component ImageText inherits Text {
    color: #d1b187;
    font-size: 32px;
    horizontal-alignment: center;
}

export component ImageDialog inherits Dialog {
    in property <string> label;
    in property <image> image;
    padding: 16px;
    VerticalLayout {
        spacing: 16px;
        alignment: center;
        Image {
            source: root.image;
            image-fit: contain;
        }

        ImageText {
            text: root.label;
        }
    }
}

export component GalleryTab {
    in property <[GameStats]> game_stats;
    in property <[GalleryItem]> gallery_items: [
        {
            level_id: 0,
            drawing_id: 0,
            title: "Level 1 sketch",
            image: @image-url("E:\\Blender\\Nodot\\images\\gallery_level1_sketch.jpg"),
        },
        {
            level_id: 0,
            drawing_id: 1,
            title: "Main character concept art",
            image: @image-url("E:\\Blender\\Nodot\\images\\gallery_mc_concept.png"),
        },
        {
            level_id: 0,
            drawing_id: 2,
            title: "Knight concept art",
            image: @image-url("E:\\Blender\\Nodot\\images\\gallery_knight_concept.jpg"),
        },
        {
            level_id: 1,
            drawing_id: 0,
            title: "Level 2 sketch",
            image: @image-url("E:\\Blender\\Nodot\\images\\gallery_level2_sketch.jpg"),
        },
        {
            level_id: 1,
            drawing_id: 1,
            title: "Early development screenshot",
            image: @image-url("E:\\Blender\\Nodot\\images\\gallery_early_screenshot.png"),
        },
        {
            level_id: 2,
            drawing_id: 0,
            title: "Level 3 sketch",
            image: @image-url("E:\\Blender\\Nodot\\images\\gallery_level3_sketch.jpg"),
        },
        {
            level_id: 2,
            drawing_id: 1,
            title: "Finishing launcher with Copilot",
            image: @image-url("E:\\Blender\\Nodot\\images\\gallery_copilot_launcher.png"),
        },
    ];
    callback request_open_image(string, image);
    ListView {
        for gallery_item in root.gallery_items: VerticalLayout {
            padding-right: 32px;
            if root.game_stats[gallery_item.level_id].unlocked_drawings[gallery_item.drawing_id]: VerticalLayout {
                padding-bottom: 16px;
                Image {
                    source: gallery_item.image;
                    max-height: 600px;
                    touch_area := TouchArea {
                        mouse-cursor: pointer;
                        clicked => {
                            root.request_open_image(gallery_item.title, gallery_item.image);
                        }
                    }
                }

                ImageText {
                    text: gallery_item.title;
                }
            }
            if !root.game_stats[gallery_item.level_id].unlocked_drawings[gallery_item.drawing_id]: VerticalLayout {
                padding-bottom: 16px;
                Rectangle {
                    width: 100%;
                    height: 435px;
                    background: #000000;
                }

                ImageText {
                    text: "???";
                }
            }
        }
    }
}
