import { ListView } from "std-widgets.slint";
import { GalleryItem ,GameStats} from "types.slint";
import { Globals } from "globals.slint";

component ImageText inherits Text {
    color: #d1b187;
    font-size: 32px;
    horizontal-alignment: center;
}

component ImageLink inherits HorizontalLayout {
    in property <string> text;
    in property <string> url;
    callback request_open_url(string);
    text := ImageText {
        text: root.text;
        touch_area := TouchArea {
            mouse-cursor: pointer;
            clicked => {
                request_open_url(root.url);
            }
        }
    }

    states [
        has-hover when touch_area.has-hover: {
            text.color: #c77b58;
        }
    ]
}

export component GalleryTab {
    in property <[GameStats]> game_stats;
    callback request_open_url(string);
    in property <[GalleryItem]> gallery_items: [
        {
            level_id: 0,
            drawing_id: 0,
            title: "Interdimensional Drift 0:0",
            author: "Author",
            image: @image-url("E:\\Blender\\Nodot\\images\\level1_screen4.png"),
            url: "https://duckduckgo.com/",
        },
        {
            level_id: 0,
            drawing_id: 1,
            title: "Interdimensional Drift 0:1",
            author: "Author",
            image: @image-url("E:\\Blender\\Nodot\\images\\level1_screen4.png"),
            url: "https://duckduckgo.com/",
        },
        {
            level_id: 0,
            drawing_id: 2,
            title: "Interdimensional Drift 0:2",
            author: "Author",
            image: @image-url("E:\\Blender\\Nodot\\images\\level1_screen4.png"),
            url: "https://duckduckgo.com/",
        },
        {
            level_id: 1,
            drawing_id: 0,
            title: "Interdimensional Drift 1:0",
            author: "Author",
            image: @image-url("E:\\Blender\\Nodot\\images\\level1_screen4.png"),
            url: "https://duckduckgo.com/",
        },
        {
            level_id: 1,
            drawing_id: 1,
            title: "Interdimensional Drift 1:1",
            author: "Author",
            image: @image-url("E:\\Blender\\Nodot\\images\\level1_screen4.png"),
            url: "https://duckduckgo.com/",
        },
        {
            level_id: 2,
            drawing_id: 0,
            title: "Interdimensional Drift 2:0",
            author: "Author",
            image: @image-url("E:\\Blender\\Nodot\\images\\level1_screen4.png"),
            url: "https://duckduckgo.com/",
        },
        {
            level_id: 2,
            drawing_id: 1,
            title: "Interdimensional Drift 2:1",
            author: "Author",
            image: @image-url("E:\\Blender\\Nodot\\images\\level1_screen4.png"),
            url: "https://duckduckgo.com/",
        },
    ];
    ListView {
        for gallery_item in root.gallery_items: VerticalLayout {
            padding-right: 32px;
            if root.game_stats[gallery_item.level_id].unlocked_drawings[gallery_item.drawing_id]: VerticalLayout {
                padding-bottom: 16px;
                Image {
                    source: gallery_item.image;
                }

                ImageLink {
                    text: gallery_item.title + " by " + gallery_item.author;
                    url: gallery_item.url;
                    request_open_url(url) => {
                        root.request_open_url(url)
                    }
                }
            }
            if !root.game_stats[gallery_item.level_id].unlocked_drawings[gallery_item.drawing_id]: VerticalLayout {
                padding-bottom: 16px;
                Rectangle {
                    width: 100%;
                    height: 435px;
                    background: #000000;
                }

                ImageText {
                    text: "???";
                }
            }
        }
    }
}
