import { ListView } from "std-widgets.slint";
import { Level } from "types.slint";
import { Globals } from "globals.slint";

component LevelText inherits Text {
    font-size: 24px;
    color: #8caba1;
}

component PlayButton inherits HorizontalLayout {
    in property <string> text;
    in property <Level> level;
    callback request_play_level(string);
    text := Text {
        text: root.text + " >";
        color: #d1b187;
        font-size: 32px;
        touch_area := TouchArea {
            mouse-cursor: pointer;
            clicked => {
                root.request_play_level(Globals.base_dir + root.level.file);
            }
        }
    }

    states [
        has-hover when touch_area.has-hover: {
            text.color: #c77b58;
        }
    ]
}

export component PlayTab {
    callback request_play_level(string);
    in property <[Level]> levels: [
        {
            name: "Interdimensional Drift",
            file: "Nodot036.blend",
            gravity: 18,
            image: @image-url("E:\\Blender\\Nodot\\images\\level1_screen4.png")
        },
        {
            name: "Jumper's High",
            file: "NodotLevel2.blend",
            gravity: 18,
            image: @image-url("E:\\Blender\\Nodot\\images\\level2_screen6.png")
        },
        {
            name: "To The Gateway",
            file: "NodotLevel3.blend",
            gravity: 14,
            image: @image-url("E:\\Blender\\Nodot\\images\\level3_screen4.png")
        }
    ];
    ListView {
        for level in root.levels: HorizontalLayout {
            spacing: 16px;
            padding-bottom: 16px;
            Image {
                source: level.image;
            }

            VerticalLayout {
                width: 40%;
                alignment: space-between;
                VerticalLayout {
                    alignment: start;
                    LevelText {
                        text: level.name;
                        font-weight: 700;
                        color: #4b726e;
                    }

                    LevelText {
                        text: "Gravity: " + level.gravity;
                    }

                    LevelText {
                        text: "Best time: 90s";
                    }

                    LevelText {
                        text: "Best gems: 70/130";
                    }

                    LevelText {
                        text: "Drawings collected: 1/3";
                    }
                }

                HorizontalLayout {
                    alignment: space-between;
                    padding-right: 32px;
                    padding-bottom: 16px;
                    Text { }

                    PlayButton {
                        text: "Start";
                        level: level;
                        request_play_level(path) => {
                            root.request_play_level(path)
                        }
                    }
                }
            }
        }
    }
}
