export struct Level {
    id: int,          // Unique identifier for the level
    name: string,
    gravity: int,
    file: string,
    image: image,
}

export struct GameStats {
    time: int,                      // Time spent on the level
    gems: int,                      // Gems collected on the level
    total_gems: int,                // Total gems available on the level
    drawings: int,                  // Drawings unlocked on the level
    total_drawings: int,            // Total drawings available on the level
    unlocked_drawings: [bool],      // Array of booleans representing unlocked drawings
}

export struct GalleryItem {
    level_id: int,
    drawing_id: int,
    title: string,
    author: string,
    image: image,
    url: string,
}

export enum MenuTab {
    None, Play, Gallery, Options, About
}
